### ISSUE TITLE
ai cheater

### ISSUE THREAD

**Issue by pat-5621-me** [Bikatr7/Bikatr7#1]
it is explicitly forbidden to use AI to take leaderboard spots away from legitimate competitors. you are not allowed to do this, and I firmly encourage you to stop before Eric Wastl decides to take justified legal action against you. you are deliberately violating the rules to make this competition worse for others and that is not okay.

Have the day you deserve.

**Comment by Bikatr7** [comment]
Not even sure what to say to this.

Please refrain from harassing me on my personal GitHub README 💀

You don't have any proof of the claims you have made, I have sufficiently explained myself [here](https://kadenbilyeu.com/blog/a3e009b8-aca5-4686-a4c5-ca016d6d0227), and you have plenty of other actual LLM cheaters (see the 30 people with sub 20-second times).

There is no legal action to take, I respect Eric immensely as someone who dedicates a lot of time to the puzzles. Now, please, stop with the witch hunt. Thank you. You're more than welcome to address and contact me individually if you'd like.

I'll be deleting this shortly, again, don't spam GitHub issues without legitimate reason as it's against TOS.
